DROP DATABASE IF EXISTS SEMINARIO;
CREATE DATABASE SEMINARIO;
USE SEMINARIO;

CREATE TABLE PERSONA(
    ID_PERSONA INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(100) not null,
    APELLIDO varchar(100) not null,
    DPI bigint(20) not null,
    NIT bigint(20),
    DIRECCION	varchar(255) not null,
    EMAIL	varchar(255) not null,
    FECHA_NACIMIENTO DATE,
    TELEFONO INT,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL
);

CREATE TABLE ROL(
    ID_ROL INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL
);

CREATE TABLE NEGOCIO(
    ID_NEGOCIO INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL
);

CREATE TABLE AREA(
    ID_AREA INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL
);

CREATE TABLE AREA_NEGOCIO(
    ID_AREA_NEGOCIO INT auto_increment PRIMARY KEY not null,
    ID_AREA INT NOT NULL,
    ID_NEGOCIO INT NOT NULL,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA),
    FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO(ID_NEGOCIO)
);

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT auto_increment PRIMARY KEY not null,
    ID_PERSONA INT NOT NULL,
    ID_ROL INT NOT NULL,
    ID_AREA_NEGOCIO INT NOT NULL,
    FECHA_INGRESO DATE,
    SUELDO INT,
    PASSWORD VARCHAR(100),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_AREA_NEGOCIO) REFERENCES AREA_NEGOCIO(ID_AREA_NEGOCIO)
);