DROP DATABASE IF EXISTS SEMINARIO;
CREATE DATABASE SEMINARIO;
USE SEMINARIO;

CREATE TABLE ROL(
    ID_ROL INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE NEGOCIO(
    ID_NEGOCIO INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE AREA(
    ID_AREA INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE AREA_NEGOCIO(
    ID_AREA_NEGOCIO INT auto_increment PRIMARY KEY not null,
    ID_AREA INT NOT NULL,
    ID_NEGOCIO INT NOT NULL,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA),
    FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO(ID_NEGOCIO)
);

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT auto_increment PRIMARY KEY not null,
    ID_ROL INT NOT NULL,
    ID_AREA_NEGOCIO INT NOT NULL,
    NOMBRE varchar(100) not null,
    APELLIDO varchar(100) not null,
    DPI bigint(20) not null,
    NIT bigint(20),
    DIRECCION	varchar(255) not null,
    EMAIL	varchar(255) not null,
    FECHA_NACIMIENTO DATE,
    TELEFONO INT,
    FECHA_INGRESO DATE,
    SUELDO INT,
    ID_SEDE INT NOT NULL,
    PASSWORD VARCHAR(255),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_AREA_NEGOCIO) REFERENCES AREA_NEGOCIO(ID_AREA_NEGOCIO)
);

CREATE TABLE SEDE(
    ID_SEDE INT auto_increment PRIMARY KEY not null,
    ID_NEGOCIO INT NOT NULL,
    DEPARTAMENTO varchar(50) not null,
    MUNICIPIO VARCHAR(100),
    DIRECCION VARCHAR(255),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO(ID_NEGOCIO)
);



/*CLIENTES Y PROVEEDORES*/
CREATE TABLE CLIENTE(
    ID_CLIENTE INT auto_increment PRIMARY KEY not null,
    ID_NEGOCIO INT NOT NULL,
    NOMBRE varchar(100) not null,
    APELLIDO varchar(100) not null,
    DPI bigint(20) not null,
    NIT bigint(20),
    DIRECCION	varchar(255) not null,
    EMAIL	varchar(255) not null,
    TELEFONO INT,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO(ID_NEGOCIO)
);

CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT auto_increment PRIMARY KEY not null,
    ID_NEGOCIO INT NOT NULL,
    NOMBRE varchar(100) not null,
    NIT bigint(20) NOT NULL,
    DIRECCION	varchar(255) not null,
    EMAIL	varchar(255) not null,
    TELEFONO INT,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIO(ID_NEGOCIO)
);







/*VENTAS*/

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE TIPO_PAGO(
    ID_TIPO_PAGO INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);



CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT auto_increment PRIMARY KEY not null,
    ID_CATEGORIA INT NOT NULL,
    ID_PROVEEDOR INT NOT NULL,
    NOMBRE varchar(255) not null,
    DESCRIPCION longtext,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK bigint NOT NULL,
    FECHA_INGRESO DATE,
    VENTA TINYINT(1),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);




CREATE TABLE FACTURA(
    ID_FACTURA INT auto_increment PRIMARY KEY not null,
    ID_CLIENTE INT NOT NULL,
    ID_TIPO_PAGO INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FECHA DATE NOT NULL,
    DIRECCION	varchar(255) not null,
    TOTAL DECIMAL(10,2) NOT NULL,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID_TIPO_PAGO)
);

CREATE TABLE DETALLE_VENTA(
    ID_DETALLE_VENTA INT auto_increment PRIMARY KEY not null,
    ID_PRODUCTO INT NOT NULL,
    ID_FACTURA INT NOT NULL,
    CANTIDAD INT NOT NULL,
    IVA DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    DESCUENTO DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);


CREATE TABLE TIPO_ALQUILER(
    ID_TIPO_ALQUILER INT auto_increment PRIMARY KEY not null,
    DESCRIPCION INT NOT NULL,
    TASA_ALQUILER DECIMAL(10,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE DETALLE_ALQUILER(
    ID_DETALLE_VENTA INT auto_increment PRIMARY KEY not null,
    ID_PRODUCTO INT NOT NULL,
    ID_FACTURA INT NOT NULL,
    TIPO_ALQUILER INT NOT NULL,
    CANTIDAD_TIPO INT NOT NULL,
    SUBTOTAL DECIMAL(10,2),
    DESCUENTO DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    FECHA_PROXIMA_FACTURACION DATE NOT NULL,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);






/*TRANSPORTES DE MATERIA PRIMA Y MAQUINARIA*/
CREATE TABLE CARGAMENTO(
    ID_CARGAMENTO INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(50) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
     ID_ELIMINO bigint(20)
);

CREATE TABLE TIPO_VEHICULO(
    ID_TIPO_VEHICULO INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(50) not null,
    EJES varchar(50),
    TONELADAS varchar(50),
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL
);

CREATE TABLE VEHICULO(
    ID_VEHICULO INT auto_increment PRIMARY KEY not null,
    ID_TIPO_VEHICULO INT NOT NULL,
    PLACA varchar(50) not null,
    MARCA varchar(100) not null,
    MODELO INT not null,
    COLOR varchar(50) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_TIPO_VEHICULO) REFERENCES TIPO_VEHICULO(ID_TIPO_VEHICULO)
);

CREATE TABLE VIAJE(
    ID_VIAJE INT auto_increment PRIMARY KEY not null,
    ID_CARGAMENTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ORIGEN VARCHAR(255) NOT NULL,
    DESTINO varchar(255) not null,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    KILOMETROS INT,
    TONELADAS INT,
    PRECIO DECIMAL(10,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_CARGAMENTO) REFERENCES CARGAMENTO(ID_CARGAMENTO)
);

CREATE TABLE ASIGNACION(
    ID_ASIGNACION INT auto_increment PRIMARY KEY not null,
    ID_VEHICULO INT NOT NULL,
    ID_VIAJE INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    ESTADO INT,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO),
    FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE(ID_VIAJE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE COMPROBANTE(
    ID_COMPROBANTE INT auto_increment PRIMARY KEY not null,
    ID_ASIGNACION INT NOT NULL,
    FECHA DATE,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION(ID_ASIGNACION)
);








/*SERVICIOS DE CONSTRUCCION*/

CREATE TABLE TIPO_OBRA(
    ID_TIPO_OBRA INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(100) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE OBRA(
    ID_OBRA INT auto_increment PRIMARY KEY not null,
    ID_TIPO_OBRA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION longtext,
    COSTO DECIMAL(15,2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_TIPO_OBRA) REFERENCES TIPO_OBRA(ID_TIPO_OBRA)
);

CREATE TABLE FASE(
    ID_FASE INT auto_increment PRIMARY KEY not null,
    ID_OBRA INT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION longtext,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    COSTO_MATERIAL DECIMAL(10,2),
    COSTO_MANO_OBRA DECIMAL(10,2),
    COSTO_TOTAL DECIMAL(12,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_OBRA) REFERENCES OBRA(ID_OBRA)
);

CREATE TABLE TIPO_MATERIAL(
    ID_TIPO_MATERIAL INT auto_increment PRIMARY KEY not null,
    NOMBRE varchar(100) not null,
    DESCRIPCION longtext,
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20)
);

CREATE TABLE MATERIAL(
    ID_MATERIAL INT auto_increment PRIMARY KEY not null,
    ID_TIPO_MATERIAL INT NOT NULL,
    ID_PROVEEDOR INT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION longtext,
    PRECIO DECIMAL(10,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_TIPO_MATERIAL) REFERENCES TIPO_MATERIAL(ID_TIPO_MATERIAL)
);

CREATE TABLE DETALLE_MATERIAL(
    ID_DETALLE_MATERIAL INT auto_increment PRIMARY KEY not null,
    ID_FASE INT NOT NULL,
    ID_MATERIAL INT NOT NULL,
    DESCRIPCION longtext,
    CANTIDAD INT,
    UNIDAD VARCHAR(150),
    PRECIO_TOTAL DECIMAL(10,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_FASE) REFERENCES FASE(ID_FASE),
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL)
);

CREATE TABLE MANO_OBRA(
    ID_MANO_OBRA INT auto_increment PRIMARY KEY not null,
    ID_FASE INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    DESCRIPCION longtext,
    COSTO DECIMAL(10,2),
    ACTIVO TINYINT(1),
    FECHA_CREACION date DEFAULT NULL,
    FECHA_ELIMINACION date DEFAULT NULL,
    ID_ELIMINO bigint(20),
    FOREIGN KEY (ID_FASE) REFERENCES FASE(ID_FASE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);